### ISSUE TITLE
New slides about vehicle hacking added

### ISSUE THREAD

**Issue by 4B5F5F4B** [jaredthecoder/awesome-vehicle-security#13]
- [A Platform base on Visualization for Protecting CAN Bus Security](https://www.syscan360.org/slides/2016_SH_Jianhao_Liu_A_platform_base_on_visualization_for_protecting_CAN_bus_security.pdf) - Syscan360 2016 SH talk by Jianhao Liu

- [Gateway Internals of Tesla Motors](https://2016.zeronights.ru/wp-content/uploads/2016/12/Gateway_Internals_of_Tesla_Motors_v6.pdf) - Zeronights 2016 talk by Nie Seng and Liu Ling

**Comment by jaredthecoder** [comment]
@4B5F5F4B Would you mind making a PR with these? :) If not, I can add them myself.

**Comment by 4B5F5F4B** [comment]
Hi,

I'm sorry that I don't know how to make a PR. I think you'd better add them
yourself. Thank you.

**Comment by jaredthecoder** [comment]
I'll add them!

**Comment by jaredthecoder** [comment]
Added in #e751753328f16b40ad4a3342c5977f9943ec7fea.
