### ISSUE TITLE
Add Hardware: Muxsan CAN Man-in-the-middle

### ISSUE THREAD

**Issue by dalathegreat** [jaredthecoder/awesome-vehicle-security#52]
Hi,
Excellent guide. My only suggestion now is to add Muxsan's CAN MITM board, extremely good tool for adding functionality / modifying your car to behave differently. Here's a link to it https://www.tindie.com/products/muxsan/can-mitm-bridge-3-port-rev-25/

I personally use these to get battery upgrades on the Nissan Leaf to work!

**Comment by jaredthecoder** [comment]
Thanks for the suggestion! I will add it.
