### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by guan4tou2** [jaredthecoder/awesome-vehicle-security#72]
[Python-CAN](http://python-can.readthedocs.io/en/latest/index.html) - Python interface to various CAN implementations, including SocketCAN. Allows you to use Python 2.7.x or 3.3.x+ to communicate over CAN networks.

This url are unavailable now, could you fix it?
https://github.com/hardbyte/python-can

**Comment by jaredthecoder** [comment]
On it!

**Comment by jaredthecoder** [comment]
And done. :)
