### ISSUE TITLE
Consider adding awesome-canbus list

### ISSUE THREAD

**Issue by serkonda7** [jaredthecoder/awesome-vehicle-security#73]
I propose mentioning https://github.com/iDoka/awesome-canbus in the README. It would fit in the _Software_ category.
It contains a lot more tools for working with CAN and various on-top protocols than are mentioned in this repo.

Alternatively adding it to the list of lists could be done.

**Comment by jaredthecoder** [comment]
Nice! I hadn't seen that yet. On it!
