### ISSUE TITLE
[awesome-vehicle-security](https://csrc.nist.gov/Projects/auto-cybersecurity-coi)

### ISSUE THREAD

**Issue by jacobdjwilson** [jaredthecoder/awesome-vehicle-security#79]
Add NIST Automotive Cybersecurity Community of Interest (COI) to websites

**Comment by jaredthecoder** [comment]
Done, thank you for sharing this @jacobdjwilson! 

https://github.com/jaredthecoder/awesome-vehicle-security/commit/474a367948ec487b770fdcf1b3d34f846d66c0fc
