### ISSUE TITLE
Project 0200 link is broken

### ISSUE THREAD

**Issue by chmac** [jaredthecoder/awesome-vehicle-security#80]
Link is https://www.vanheusden.com/O2OO/ which generates a 404 for me...

**Comment by GR8DAN** [comment]
Looks like it disappeared sometime after 08/11/2020:

http://web.archive.org/web/20201108091723/https://www.vanheusden.com/O2OO/

**Comment by jaredthecoder** [comment]
I will replace it now.

**Comment by jaredthecoder** [comment]
Redirected to the wayback machine. Thank you @GR8DAN!
