### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [jaredthecoder/awesome-vehicle-security#81]
Hello, I found some broken links:

- [ ] http://bigdata-madesimple.com/big-data-will-impact-car-security-proximate-future-concerns-solutions/ (file: README.md, error: ENOTFOUND)
- [x] https://www.syscan360.org/slides/2016_SH_Jianhao_Liu_A_platform_base_on_visualization_for_protecting_CAN_bus_security.pdf (file: README.md, error: ENOTFOUND)
- [x] https://2016.zeronights.ru/wp-content/uploads/2016/12/Gateway_Internals_of_Tesla_Motors_v6.pdf (file: README.md, error: ECONNREFUSED)
- [x] http://opengarages.org/handbook/ (file: README.md, error: EAI_AGAIN)
- [x] https://unicorn.360.com/blog/2018/01/29/Inside_Radio_An_Attack_and_Defense_Guide (file: README.md, error: ECONNRESET)
- [x] https://awesong-kor.github.io/files/Intrusion%20Detection%20System%20Based%20on%20the%20Analysis%20of%20Time%20Intervals%20of%20CAN%20Messages%20for%20In-Vehicle%20Network.pdf (file: README.md, status code: 404)
- [x] http://opengarages.org/index.php/Main_Page (file: README.md, error: EAI_AGAIN)
- [x] https://www.trustedsec.com/podcast/ (file: README.md, status code: 404)
- [x] https://hackablepodcast.com/#/episodes/cars-are-computers (file: README.md, error: CERT_HAS_EXPIRED)
- [x] http://www.seeedstudio.com/wiki/CAN-BUS_Shield (file: README.md, status code: 404)
- [x] http://linklayer.github.io/cantact/ (file: README.md, status code: 404)
- [x] https://canb.us/ (file: README.md, error: CERT_HAS_EXPIRED)
- [x] http://macchina.cc/guide/m2 (file: README.md, status code: 404)
- [x] https://www.uberatc.com/ (file: README.md, error: ECONNRESET)
- [x] https://bugcrowd.com/fca (file: README.md, status code: 404)

**Comment by jaredthecoder** [comment]
Thank you for this @ndsvw, I will go through them. :)

**Comment by shipcod3** [comment]
FCA's bug bounty program has been moved to https://bugcrowd.com/stellantis

**Comment by jaredthecoder** [comment]
I merged your commit @shipcod3. Thank you! A bunch of these were old and I did just update them - some I couldn't find and should have downloaded at the time. It's been almost a decade since I made this repo. It's crazy how long it's been.

**Comment by jaredthecoder** [comment]
I will close this for now and try to find some time to do another audit.

**Comment by shipcod3** [comment]
> I merged your commit @shipcod3. Thank you! A bunch of these were old and I did just update them - some I couldn't find and should have downloaded at the time. It's been almost a decade since I made this repo. It's crazy how long it's been.

Thanks, and your welcome. It's one of the most awesome repos for car hacking and automotive security. Whenever, I give a training or a talk related to this subject, I always add this link to my talk. Thanks for maintaining this list :)
