### ISSUE TITLE
Please help reverse effects of canbus car hack

### ISSUE THREAD

**Issue by ghost** [jaredthecoder/awesome-vehicle-security#82]
Hi,

Hopefully you can help. 

Some help is much needed and appreciated. I'm a 45 year old disabled man that lives in Faringdon, Oxfordshire. The disabilities are severe sensory PTSD, agoraphobia and psychogenic hyperventilation.

Since earlier this year the motability Golf has been hacked by people with anti-disability vendettas. They've accessed the canbus remotely so the suspension wallows, shudders and porpoises over undulations. Extensive research was conducted and I'm desperate for the hacking to stop. It's ruining what little quality of life there is.

Can Savvy seems to be able to access various canbus to alter settings? Please can you advise how it can be used to reverse the affects to the suspension? They've also altered another canbus so there's excessive noise and vibration through pedals and steering. Dealer resets haven't worked. All help is much appreciated. It would be much appreciated if we could arrange a video call so I can be shown how to address the issues.

Many thanks in advance,

Josh Ross

**Comment by 4B5F5F4B** [comment]
Do you mean that some hackers some hakcers remotedly access your cars' canbus?

**Comment by jsr1978** [comment]
Yes, that's what's happened - please read above. Would you or anyone else be able to help? Research suggests that cansavvy and other similar programmes can alter car behaviours like ride/handling through canbus adjustments. I don't know how to use the programmes so some guidance is very much appreciated. An ob2 port was ordered from Amazon (variety as suggested by user jgamblin - carhackingtool). Beyond that I don't know how to interact with and adjust settings with various canbus.

Thanks,

Josh

**Comment by 4B5F5F4B** [comment]
Hello Josh,

As far as I know, it's almost impossible to send CAN bus message remotely. Hackers can only send can bus to your cars ecu locally, unless they have hacked your IVI remotely. Would you mind give me more information about your car? What model and brand is your car?

**Comment by jaredthecoder** [comment]
Deleting this issue due to a data removal request from Github.
